[project]
name = "gamepicker"
version = "0.1.0"
description = "Used for generating game lists"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.3.1",
    "numpy>=2.4.0",
    "jsonpickle>=4.1.1",
    "webcolors>=25.10.0",
    "pillow>=12.0.0",
    "pyspellchecker>=0.8.4",
    "ujson>=5.11.0",
    "gamemaster",
]

[tool.uv.sources]
gamemaster = { path = "../GameMaster" }