from enum import Enum


class Selector(Enum):
    _2D_PLATFORMERS = "2D Platformers"
    _3D_PLATFORMERS = "3D Platformers"
    AAA_GAMES = "AAA Games"
    ACTION_ADVENTURE_GAMES = "Action Adventure Games"
    ALL_GAMES = "All Games"
    ALPHABETICAL = "Alphabetical"
    ALTERNATE_EDITIONS = "Alternate Editions"
    BACKLOGGD_TOP = "Backloggd Top"
    BEAT_EM_UPS = "Beat 'em Ups"
    BEST_BY_GENRE = "Best By Genre"
    BEST_BY_PLATFORM = "Best By Platform"
    BEST_BY_YEAR = "Best By Year"
    BEST_COMPANIES_BY_METACRITIC = "Best Companies By Metacritic"
    BEST_YEARS_BY_METACRITIC = "Best Years By Metacritic"
    BETWEEN_1_AND_5_HOURS = "Between 1 and 5 Hours"
    BETWEEN_5_AND_10_HOURS = "Between 5 and 10 Hours"
    BETWEEN_10_AND_20_HOURS = "Between 10 and 20 Hours"
    BETWEEN_20_AND_30_HOURS = "Between 20 and 30 Hours"
    BIG_GAMES = "Big Games"
    BIRTHDAY_GAMES = "Birthday Games"
    BOOMER_SHOOTERS = "Boomer Shooters"
    COLLECTIONS = "Collections"
    COMPLETED_GAMES_ORDERING = "Completed Games Ordering"
    COMPLETED_VALUES = "Completed Values"
    COOP_GAMES = "Coop Games"
    CYBERPUNK = "Cyberpunk"
    DAD_GAMES = "Dad Games"
    DELISTED_GAMES = "Delisted Games"
    DLCS = "DLCs"
    FAN_TRANSLATIONS = "Fan Translations"
    FAVORITES = "Favorites"
    FIGHTING_GAMES = "Fighting Games"
    FIRST_PARTY_GAMES = "First Party Games"
    FRANCHISE_PLAYTHROUGH_CONTENDERS = "Franchise Playthrough Contenders"
    FRANCHISE_PLAYTHROUGHS = "Franchise Playthroughs"
    FREEWARE = "Freeware"
    FROMSOFTWARE = "FromSoftware"
    GAMES_ON_ORDER = "Games on Order"
    GREATER_THAN_30_HOURS = "Greater Than 30 Hours"
    HACK_AND_SLASH = "Hack-and-Slash"
    HIGHEST_PRIORITY_PLATFORMS = "Highest Priority Platforms"
    HIGH_CRITIC_RATINGS = "High Critic Ratings"
    HIGH_PRIORITY_RATINGS = "High Priority Ratings"
    HIGH_USER_RATINGS = "High User Ratings"
    HORROR_GAMES = "Horror Games"
    IMMERSIVE_SIMS = "Immersive Sims"
    INCOMPLETE_COLLECTIONS = "Incomplete Collections"
    JRPG = "JRPG"
    LARGEST_RATING_DIFFERENCES = "Largest Rating Differences"
    LIMITED_PRINT_GAMES = "Limited Print Games"
    LONGEST_GAMES = "Longest Games"
    LONGEST_PLAYTHROUGHS = "Longest Playthroughs"
    LONGEST_TITLES = "Longest Titles"
    MAJOR_INDIE_GAMES = "Major Indie Games"
    MAX_PRIORITY = "Max Priority"
    METROIDVANIA = "Metroidvania"
    MISSING_PLAYTIME = "Missing Playtime"
    MISSPELLINGS = "Misspellings"
    MOST_CONCURRENT_PLAYTHROUGHS = "Most Concurrent Playthroughs"
    MOST_PLAYED_DEVELOPERS = "Most Played Developers"
    MOST_PLAYED_FRANCHISES = "Most Played Franchises"
    MOST_PLAYED_GENRES = "Most Played Genres"
    MOST_PLAYED_PLATFORMS = "Most Played Platforms"
    MOST_PLAYED_YEARS = "Most Played Years"
    NO_ESTIMATED_PLAYTIME = "No Estimated Playtime"
    NON_DOWNLOADED_GAMES = "Non-Downloaded Games"
    NON_STEAM = "Non-Steam"
    NOW_PLAYING = "Now Playing"
    OBSCURE_GAMES = "Obscure Games"
    OFFBEAT_GENRE_GAMES = "Offbeat Genre Games"
    ONE_PER_ADDED_DATE_CHALLENGE = "One Per Added Date Challenge"
    ONE_PER_ADDED_DATE_CHALLENGE_COMPLETIONS = (
        "One Per Added Date Challenge Completions"
    )
    ONE_PER_ALPHABET_CHALLENGE = "One Per Alphabet Challenge"
    ONE_PER_ALPHABET_CHALLENGE_COMPLETIONS = "One Per Alphabet Challenge Completions"
    ONE_PER_FAN_TRANSLATION_CHALLENGE = "One Per Fan Translation Challenge"
    ONE_PER_FAN_TRANSLATION_CHALLENGE_COMPLETIONS = (
        "One Per Fan Translation Challenge Completions"
    )
    ONE_PER_FRANCHISE_CONTENDER_CHALLENGE = "One Per Franchise Contender Challenge"
    ONE_PER_FRANCHISE_CONTENDER_CHALLENGE_COMPLETIONS = (
        "One Per Franchise Contender Challenge Completions"
    )
    ONE_PER_GENRE_CHALLENGE = "One Per Genre Challenge"
    ONE_PER_GENRE_CHALLENGE_COMPLETIONS = "One Per Genre Challenge Completions"
    ONE_PER_LIMITED_PRINT_CHALLENGE = "One Per Limited Print Challenge"
    ONE_PER_LIMITED_PRINT_CHALLENGE_COMPLETIONS = (
        "One Per Limited Print Challenge Completions"
    )
    ONE_PER_PERCENTILE_CHALLENGE = "One Per Percentile Challenge"
    ONE_PER_PERCENTILE_CHALLENGE_COMPLETIONS = (
        "One Per Percentile Challenge Completions"
    )
    ONE_PER_PLATFORM_CHALLENGE = "One Per Platform Challenge"
    ONE_PER_PLATFORM_CHALLENGE_COMPLETIONS = "One Per Platform Challenge Completions"
    ONE_PER_PLATFORM_CHALLENGE_UNPLAYABLE = "One Per Platform Challenge Unplayable"
    ONE_PER_PLAYTIME_CHALLENGE = "One Per Playtime Challenge"
    ONE_PER_PLAYTIME_CHALLENGE_COMPLETIONS = "One Per Playtime Challenge Completions"
    ONE_PER_PURCHASE_DATE_CHALLENGE = "One Per Purchase Date Challenge"
    ONE_PER_PURCHASE_DATE_CHALLENGE_COMPLETIONS = (
        "One Per Purchase Date Challenge Completions"
    )
    ONE_PER_PURCHASE_PRICE_CHALLENGE = "One Per Purchase Price Challenge"
    ONE_PER_PURCHASE_PRICE_CHALLENGE_COMPLETIONS = (
        "One Per Purchase Price Challenge Completions"
    )
    ONE_PER_RATING_CHALLENGE = "One Per Rating Challenge"
    ONE_PER_RATING_CHALLENGE_COMPLETIONS = "One Per Rating Challenge Completions"
    ONE_PER_REGION_CHALLENGE = "One Per Region Challenge"
    ONE_PER_REGION_CHALLENGE_COMPLETIONS = "One Per Region Challenge Completions"
    ONE_PER_TITLE_LENGTH_CHALLENGE = "One Per Title Length Challenge"
    ONE_PER_TITLE_LENGTH_CHALLENGE_COMPLETIONS = (
        "One Per Title Length Challenge Completions"
    )
    ONE_PER_TOP_DEVELOPER_CHALLENGE = "One Per Top Developer Challenge"
    ONE_PER_TOP_DEVELOPER_CHALLENGE_COMPLETIONS = (
        "One Per Top Developer Challenge Completions"
    )
    ONE_PER_YEAR_CHALLENGE = "One Per Year Challenge"
    ONE_PER_YEAR_CHALLENGE_COMPLETIONS = "One Per Year Challenge Completions"
    PALINDROMES = "Palindromes"
    PERCENTILES = "Percentiles"
    PHYSICAL_GAMES = "Physical Games"
    PICROSS = "Picross"
    PLATFORM_PROGRESS = "Platform Progress"
    PLAYED_PURCHASES = "Played Purchases"
    POINT_AND_CLICK_GAMES = "Point and Click Games"
    POTENTIAL_DUPLICATES = "Potential Duplicates"
    PURCHASE_TO_COMPLETION_GAPS = "Purchase to Completion Gaps"
    PUZZLE_GAMES = "Puzzle Games"
    QUARTERLY_SPEND = "Quarterly Spend"
    RAIL_SHOOTERS = "Rail Shooters"
    RUN_AND_GUN = "Run and Gun"
    S_GAMES = "S Games"
    SAN_FRANCISCO_GAMES = "San Francisco Games"
    SELECTORS_BY_GENRE = "Selectors By Genre"
    SELECTORS_BY_PLATFORM = "Selectors By Platform"
    SHEET_VALIDATIONS = "Sheet Validations"
    SHMUPS = "Shmups"
    SHORTEST_BY_GENRE = "Shortest By Genre"
    SHORTEST_BY_YEAR = "Shortest By Year"
    SHORTEST_GAMES = "Shortest Games"
    SHORTEST_OVERALL = "Shortest Overall"
    SHORTEST_OVERALL_UNCOMMON_GENRE = "Shortest Overall - Uncommon Genre"
    SOULSLIKES = "Soulslikes"
    STRATEGY_GAMES = "Strategy Games"
    SUBSCRIPTIONS = "Subscriptions"
    SURVIVORS_LIKES = "Survivors Likes"
    TOP_BY_SELECTOR = "Top By Selector"
    TOP_GAMES = "Top Games"
    TOP_TEN_JRPGS = "Top 10 JRPGs"
    UNDER_1_HOUR = "Under 1 Hour"
    UNDER_1_HOUR_UNCOMMON_GENRE = "Under 1 Hour - Uncommon Genre"
    UNDERPRIORITIZED = "Underprioritized"
    UNORDERED_AMAZON_GAMES = "Unordered Amazon Games"
    UNOWNED_PC_GAMES = "Unowned PC Games"
    UNKNOWN_PLAYABILITY = "Unknown Playability"
    UNPLAYABLE_HIGH_PRIORITY = "Unplayable High Priority"
    UNPLAYABLE_LOW_PRIORITY = "Unplayable Low Priority"
    UNPLAYED_PURCHASES = "Unplayed Purchases"
    UNPLAYED_WISHLISTED = "Unplayed Wishlisted"
    UNTRANSLATED_GAMES = "Untranslated Games"
    VEHICLE_BASED_GAMES = "Vehicle Based Games"
    VERY_BAD_GAMES = "Very Bad Games"
    VERY_POSITIVE_GAMES = "Very Positive Games"
    VIRTUAL_CONSOLE = "Virtual Console"
    VISUAL_NOVELS = "Visual Novels"
    VR = "VR"
    WILL_NOT_PLAY = "Will Not Play"
    ZACH_GAMES = "Zach Games"
    ZERO_PERCENT = "Zero Percent"
