from excel_game import ExcelGenre
from game_match import DataSource

GENRE_MAPPINGS = {
    DataSource.ARCADE_DATABASE: {
        "Computer / Home System": None,
        "Driving / 1st Person": ExcelGenre.RACING,
        "Driving / Ambulance Guide": ExcelGenre.RACING,
        "Driving / Boat": ExcelGenre.RACING,
        "Driving / Guide and Shoot": ExcelGenre.RACING,
        "Driving / Plane": ExcelGenre.FLIGHT_SIMULATION,
        "Driving / Race (chase view)": ExcelGenre.RACING,
        "Driving / Race 1st Person": ExcelGenre.RACING,
        "Driving / Race Track": ExcelGenre.RACING,
        "Electromechanical / Pinball": ExcelGenre.PINBALL,
        "Fighter / 2.5D": ExcelGenre.FIGHTING,
        "Fighter / 2D": ExcelGenre.FIGHTING,
        "Fighter / 3D": ExcelGenre.FIGHTING,
        "Fighter / Driving Vertical": ExcelGenre.FIGHTING,
        "Fighter / Misc.": ExcelGenre.FIGHTING,
        "Fighter / Versus": ExcelGenre.FIGHTING,
        "Fighter / Versus Co-op": ExcelGenre.FIGHTING,
        "Fighter / Vertical": ExcelGenre.FIGHTING,
        "Handheld / Electronic Game": None,
        "Handheld / Home Videogame Console": None,
        "Handheld / Plug n' Play TV Game": None,
        "Handheld / Plug n' Play TV Game / Action": ExcelGenre.ACTION,
        "Handheld / Plug n' Play TV Game / Puzzle": ExcelGenre.PUZZLE,
        "Maze / Collect": ExcelGenre.ARCADE,
        "Maze / Digging": ExcelGenre.ARCADE,
        "Maze / Fighter": ExcelGenre.ARCADE,
        "Maze / Shooter Large": ExcelGenre.ARCADE,
        "Platform / Fighter": ExcelGenre.FIGHTING,
        "Platform / Fighter Scrolling": ExcelGenre.FIGHTING,
        "Platform / Run Jump": ExcelGenre.SIDE_SCROLLING_PLATFORMER,
        "Platform / Run, Jump & Scrolling": ExcelGenre.SIDE_SCROLLING_PLATFORMER,
        "Platform / Shooter Scrolling": ExcelGenre.ACTION_PLATFORMER,
        "Puzzle / Drop": ExcelGenre.PUZZLE,
        "Puzzle / Toss": ExcelGenre.PUZZLE,
        "Quiz / Questions in English": ExcelGenre.BOARD_GAME,
        "Shooter / 1st Person": ExcelGenre.RAIL_SHOOTER,
        "Shooter / 3rd Person": ExcelGenre.THIRD_PERSON_SHOOTER,
        "Shooter / Driving (chase view)": ExcelGenre.VEHICULAR_COMBAT,
        "Shooter / Driving Vertical": ExcelGenre.SCROLLING_SHOOTER,
        "Shooter / Field": ExcelGenre.SHOOTER,
        "Shooter / Flying": ExcelGenre.SCROLLING_SHOOTER,
        "Shooter / Flying (chase view)": ExcelGenre.SCROLLING_SHOOTER,
        "Shooter / Flying 1st Person": ExcelGenre.RAIL_SHOOTER,
        "Shooter / Flying Horizontal": ExcelGenre.SCROLLING_SHOOTER,
        "Shooter / Flying Vertical": ExcelGenre.SCROLLING_SHOOTER,
        "Shooter / Gallery": ExcelGenre.RAIL_SHOOTER,
        "Shooter / Gun": ExcelGenre.RAIL_SHOOTER,
        "Shooter / Misc.": ExcelGenre.SHOOTER,
        "Shooter / Walking": ExcelGenre.RUN_AND_GUN,
        "Slot Machine / Video Slot": None,
        "Sports / Boxing": ExcelGenre.SPORTS,
        "Sports / Misc.": ExcelGenre.SPORTS,
        "Watch / LCD Game": None,
    },
    DataSource.COOPTIMUS: {
        "Action": ExcelGenre.ACTION,
        "Action RPG": ExcelGenre.ACTION_RPG,
        "Action/Adventure": ExcelGenre.ACTION_ADVENTURE,
        "Action/RTS": ExcelGenre.REAL_TIME_STRATEGY,
        "Adventure": ExcelGenre.ADVENTURE,
        "Arcade": ExcelGenre.ARCADE,
        "Beat-Em-Up": ExcelGenre.BEAT_EM_UP,
        "Card Combat": ExcelGenre.CARD_GAME,
        "Compilations": ExcelGenre.COMPILATION,
        "Driving": ExcelGenre.RACING,
        "Driving/Vehicular Combat": ExcelGenre.VEHICULAR_COMBAT,
        "Fighting": ExcelGenre.FIGHTING,
        "First Person Shooter": ExcelGenre.FIRST_PERSON_SHOOTER,
        "First Person/RTS": ExcelGenre.REAL_TIME_STRATEGY,
        "Flight": ExcelGenre.FLIGHT_SIMULATION,
        "Grand Strategy": ExcelGenre.GRAND_STRATEGY,
        "MMO": ExcelGenre.MMORPG,
        "Mech Simulation": ExcelGenre.VEHICULAR_COMBAT,
        "Minigames": ExcelGenre.MINIGAME_COLLECTION,
        "Music/Rhythm": ExcelGenre.RHYTHM,
        "On-Rails Shooter": ExcelGenre.RAIL_SHOOTER,
        "Platform Shooter": ExcelGenre.RUN_AND_GUN,
        "Platformer": ExcelGenre.SIDE_SCROLLING_PLATFORMER,
        "Puzzle": ExcelGenre.PUZZLE,
        "Puzzle Platformer": ExcelGenre.PUZZLE_PLATFORMER,
        "RPG": ExcelGenre.TURN_BASED_RPG,
        "RTS": ExcelGenre.REAL_TIME_STRATEGY,
        "Racing": ExcelGenre.RACING,
        "Relaxing Experience": ExcelGenre.EXPERIMENTAL,
        "Sandbox": ExcelGenre.SIMULATION,
        "Shmup": ExcelGenre.SCROLLING_SHOOTER,
        "Side Scroller": ExcelGenre.SIDE_SCROLLING_PLATFORMER,
        "Simulation": ExcelGenre.SIMULATION,
        "Sports": ExcelGenre.SPORTS,
        "Stealth Action": ExcelGenre.STEALTH_ACTION,
        "Surgery Simulation": ExcelGenre.SIMULATION,
        "Survival": ExcelGenre.SURVIVAL,
        "Survival Horror": ExcelGenre.SURVIVAL_HORROR,
        "Tactical FPS": ExcelGenre.TACTICAL_SHOOTER,
        "Tactical RPG": ExcelGenre.STRATEGY_RPG,
        "Third Person Shooter": ExcelGenre.THIRD_PERSON_SHOOTER,
        "Tower Defense": ExcelGenre.TOWER_DEFENSE,
        "Turn Based Strategy": ExcelGenre.TURN_BASED_STRATEGY,
        "Twin Stick Shooter": ExcelGenre.TWIN_STICK_SHOOTER,
    },
    DataSource.GAME_FAQS: {
        "Action > Arcade": ExcelGenre.ARCADE,
        "Action > Beat-'Em-Up > 2D": ExcelGenre.BEAT_EM_UP,
        "Action > Beat-'Em-Up > 3D": ExcelGenre.BEAT_EM_UP,
        "Action > Fighting > 2D": ExcelGenre.FIGHTING,
        "Action > Fighting > 3D": ExcelGenre.FIGHTING,
        "Action > General": ExcelGenre.ACTION,
        "Action > Pinball": ExcelGenre.PINBALL,
        "Action > Platformer > 2D": ExcelGenre.ACTION_PLATFORMER,
        "Action > Platformer > 3D": ExcelGenre._3D_PLATFORMER,
        "Action > Platformer > Metroidvania": ExcelGenre.METROIDVANIA,
        "Action > Rhythm > Dancing": ExcelGenre.RHYTHM,
        "Action > Rhythm > Music": ExcelGenre.RHYTHM,
        "Action > Shooter > First-Person > Arcade": ExcelGenre.FIRST_PERSON_SHOOTER,
        "Action > Shooter > First-Person > Tactical": ExcelGenre.FIRST_PERSON_SHOOTER,
        "Action > Shooter > Light Gun": ExcelGenre.RAIL_SHOOTER,
        "Action > Shooter > Rail": ExcelGenre.RAIL_SHOOTER,
        "Action > Shooter > Shoot-'Em-Up > Horizontal": ExcelGenre.SCROLLING_SHOOTER,
        "Action > Shooter > Shoot-'Em-Up > Top-Down": ExcelGenre.SCROLLING_SHOOTER,
        "Action > Shooter > Shoot-'Em-Up > Vertical": ExcelGenre.SCROLLING_SHOOTER,
        "Action > Shooter > Third-Person > Arcade": ExcelGenre.THIRD_PERSON_SHOOTER,
        "Action > Shooter > Third-Person > Tactical": ExcelGenre.TACTICAL_SHOOTER,
        "Action Adventure > General": ExcelGenre.ACTION_ADVENTURE,
        "Action Adventure > Linear": ExcelGenre.ACTION_ADVENTURE,
        "Action Adventure > Open-World": ExcelGenre.ACTION_ADVENTURE,
        "Action Adventure > Sandbox": ExcelGenre.ACTION_ADVENTURE,
        "Action Adventure > Survival": ExcelGenre.ACTION_ADVENTURE,
        "Adventure > 3D > First-Person": ExcelGenre.FIRST_PERSON_ACTION,
        "Adventure > 3D > Third-Person": ExcelGenre.THIRD_PERSON_ACTION,
        "Adventure > General": ExcelGenre.ADVENTURE,
        "Adventure > Point-and-Click": ExcelGenre.ADVENTURE,
        "Adventure > Text": ExcelGenre.TEXT_ADVENTURE,
        "Adventure > Visual Novel": ExcelGenre.VISUAL_NOVEL,
        "Miscellaneous > Application": None,
        "Miscellaneous > Board / Card Game": [
            ExcelGenre.CARD_GAME,
            ExcelGenre.BOARD_GAME,
        ],
        "Miscellaneous > Compilation": ExcelGenre.COMPILATION,
        "Miscellaneous > Edutainment": ExcelGenre.EDUCATIONAL,
        "Miscellaneous > Exercise / Fitness": ExcelGenre.SPORTS,
        "Miscellaneous > Gambling": None,
        "Miscellaneous > General": ExcelGenre.EXPERIMENTAL,
        "Miscellaneous > Party / Minigame": ExcelGenre.MINIGAME_COLLECTION,
        "Miscellaneous > Trivia / Game Show": ExcelGenre.TRIVIA,
        "Puzzle > Action": ExcelGenre.PUZZLE_ACTION,
        "Puzzle > General": ExcelGenre.PUZZLE,
        "Puzzle > Hidden Object": ExcelGenre.HIDDEN_OBJECT,
        "Puzzle > Logic": ExcelGenre.PUZZLE,
        "Puzzle > Matching": ExcelGenre.PUZZLE,
        "Puzzle > Stacking": ExcelGenre.PUZZLE,
        "Racing > Arcade > Automobile": ExcelGenre.RACING,
        "Racing > Arcade > Futuristic": ExcelGenre.RACING,
        "Racing > Arcade > Other": ExcelGenre.RACING,
        "Racing > General": ExcelGenre.RACING,
        "Racing > Simulation > Automobile": ExcelGenre.RACING,
        "Role-Playing > Action RPG": ExcelGenre.ACTION_RPG,
        "Role-Playing > General": ExcelGenre.TURN_BASED_RPG,
        "Role-Playing > Japanese-Style": ExcelGenre.TURN_BASED_RPG,
        "Role-Playing > Massively Multiplayer": ExcelGenre.MMORPG,
        "Role-Playing > Roguelike": ExcelGenre.ROGUELIKE,
        "Role-Playing > Trainer": ExcelGenre.TURN_BASED_RPG,
        "Role-Playing > Western-Style": ExcelGenre.COMPUTER_RPG,
        "Simulation > Flight > Civilian": ExcelGenre.FLIGHT_SIMULATION,
        "Simulation > Flight > Combat": ExcelGenre.FLIGHT_SIMULATION,
        "Simulation > General": ExcelGenre.SIMULATION,
        "Simulation > Marine > Civilian": ExcelGenre.SIMULATION,
        "Simulation > Marine > Combat": ExcelGenre.SIMULATION,
        "Simulation > Space > Civilian": ExcelGenre.SPACE_COMBAT,
        "Simulation > Space > Combat": ExcelGenre.SPACE_COMBAT,
        "Simulation > Vehicle > Civilian": ExcelGenre.RACING,
        "Simulation > Vehicle > Combat": ExcelGenre.VEHICULAR_COMBAT,
        "Simulation > Virtual > Career": ExcelGenre.SIMULATION,
        "Simulation > Virtual > Pet": ExcelGenre.SIMULATION,
        "Simulation > Virtual > Virtual Life": ExcelGenre.SIMULATION,
        "Sports > General": ExcelGenre.SPORTS,
        "Sports > Individual > Athletics": ExcelGenre.SPORTS,
        "Sports > Individual > Biking": ExcelGenre.SPORTS,
        "Sports > Individual > Combat > Boxing / Martial Arts": ExcelGenre.SPORTS,
        "Sports > Individual > Combat > Wrestling": ExcelGenre.SPORTS,
        "Sports > Individual > Golf > Arcade": ExcelGenre.SPORTS,
        "Sports > Individual > Golf > Sim": ExcelGenre.SPORTS,
        "Sports > Individual > Nature > Fishing": ExcelGenre.SPORTS,
        "Sports > Individual > Nature > Hunting": ExcelGenre.SPORTS,
        "Sports > Individual > Other": ExcelGenre.SPORTS,
        "Sports > Individual > Skate / Skateboard": ExcelGenre.SPORTS,
        "Sports > Individual > Ski / Snowboard": ExcelGenre.SPORTS,
        "Sports > Individual > Surf / Wakeboard": ExcelGenre.SPORTS,
        "Sports > Individual > Tennis": ExcelGenre.SPORTS,
        "Sports > Team > Baseball > Arcade": ExcelGenre.SPORTS,
        "Sports > Team > Basketball > Arcade": ExcelGenre.SPORTS,
        "Sports > Team > Basketball > Sim": ExcelGenre.SPORTS,
        "Sports > Team > Football > Arcade": ExcelGenre.SPORTS,
        "Sports > Team > Football > Sim": ExcelGenre.SPORTS,
        "Sports > Team > Futuristic": ExcelGenre.SPORTS,
        "Sports > Team > Other": ExcelGenre.SPORTS,
        "Sports > Team > Soccer > Arcade": ExcelGenre.SPORTS,
        "Sports > Team > Soccer > Management": ExcelGenre.SPORTS,
        "Sports > Team > Volleyball": ExcelGenre.SPORTS,
        "Strategy > General": ExcelGenre.STRATEGY,
        "Strategy > Management > Business / Tycoon": ExcelGenre.SIMULATION,
        "Strategy > Management > Government": ExcelGenre.SIMULATION,
        "Strategy > Real-Time > Command": ExcelGenre.REAL_TIME_STRATEGY,
        "Strategy > Real-Time > Defense": ExcelGenre.REAL_TIME_STRATEGY,
        "Strategy > Real-Time > General": ExcelGenre.REAL_TIME_STRATEGY,
        "Strategy > Real-Time > MOBA": None,
        "Strategy > Real-Time > Tactics": ExcelGenre.REAL_TIME_TACTICS,
        "Strategy > Turn-Based > 4X": ExcelGenre._4X,
        "Strategy > Turn-Based > Card Battle": ExcelGenre.CARD_GAME,
        "Strategy > Turn-Based > General": ExcelGenre.STRATEGY_RPG,
        "Strategy > Turn-Based > Tactics": ExcelGenre.TURN_BASED_TACTICS,
    },
    DataSource.GAME_SPOT: {
        "2D Action Beat-'Em-Up": ExcelGenre.BEAT_EM_UP,
        "2D Action Beat-'Em-Up VR": ExcelGenre.BEAT_EM_UP,
        "2D Action Fighting": ExcelGenre.FIGHTING,
        "2D Action Fixed-Screen Shooter": ExcelGenre.SHOOTER,
        "2D Action Fixed-Screen Shooter VR": ExcelGenre.SHOOTER,
        "2D Action Platformer": ExcelGenre.ACTION_PLATFORMER,
        "2D Action Platformer Roguelike": [
            ExcelGenre.ACTION_PLATFORMER,
            ExcelGenre.ROGUELIKE,
        ],
        "2D Action Shoot-'Em-Up": ExcelGenre.SCROLLING_SHOOTER,
        "2D Action Shooter": ExcelGenre.SCROLLING_SHOOTER,
        "3D Action Adventure": ExcelGenre.ACTION_ADVENTURE,
        "3D Action Adventure First-Person Open-World Shooter Third-Person": [
            ExcelGenre.ACTION_ADVENTURE,
            ExcelGenre.FIRST_PERSON_ACTION,
            ExcelGenre.THIRD_PERSON_SHOOTER,
        ],
        "3D Action Adventure First-Person Shooter Survival": [
            ExcelGenre.ACTION_ADVENTURE,
            ExcelGenre.FIRST_PERSON_SHOOTER,
            ExcelGenre.SURVIVAL,
        ],
        "3D Action Adventure Open-World": ExcelGenre.ACTION_ADVENTURE,
        "3D Action Adventure Open-World Roguelike": [
            ExcelGenre.ACTION_ADVENTURE,
            ExcelGenre.ROGUELIKE,
        ],
        "3D Action Adventure Roguelike": [
            ExcelGenre.ACTION_ADVENTURE,
            ExcelGenre.ROGUELIKE,
        ],
        "3D Action Adventure Role-Playing Third-Person": [
            ExcelGenre.ACTION_ADVENTURE,
            ExcelGenre.ACTION_RPG,
            ExcelGenre.THIRD_PERSON_ACTION,
        ],
        "3D Action Adventure Survival": [
            ExcelGenre.ACTION_ADVENTURE,
            ExcelGenre.SURVIVAL,
        ],
        "3D Action Adventure Survival VR": [
            ExcelGenre.ACTION_ADVENTURE,
            ExcelGenre.SURVIVAL,
        ],
        "3D Action Adventure Third-Person": [
            ExcelGenre.ACTION_ADVENTURE,
            ExcelGenre.THIRD_PERSON_ACTION,
        ],
        "3D Action Beat-'Em-Up": ExcelGenre.BEAT_EM_UP,
        "3D Action Beat-'Em-Up VR": ExcelGenre.BEAT_EM_UP,
        "3D Action Fighting": ExcelGenre.FIGHTING,
        "3D Action Fighting Party/Minigame": ExcelGenre.FIGHTING,
        "3D Action Fighting VR": ExcelGenre.FIGHTING,
        "3D Action First-Person Role-Playing Shooter": [
            ExcelGenre.FIRST_PERSON_ACTION,
            ExcelGenre.ACTION_RPG,
        ],
        "3D Action First-Person Shooter": ExcelGenre.FIRST_PERSON_SHOOTER,
        "3D Action First-Person Shooter Tactical": [
            ExcelGenre.FIRST_PERSON_SHOOTER,
            ExcelGenre.TACTICAL_SHOOTER,
        ],
        "3D Action First-Person Shooter Team-Based": ExcelGenre.FIRST_PERSON_SHOOTER,
        "3D Action First-Person Shooter VR": ExcelGenre.FIRST_PERSON_SHOOTER,
        "3D Action On-Rails Shooter": ExcelGenre.RAIL_SHOOTER,
        "3D Action On-Rails Shooter VR": ExcelGenre.RAIL_SHOOTER,
        "3D Action Platformer": ExcelGenre._3D_PLATFORMER,
        "3D Action Platformer VR": ExcelGenre._3D_PLATFORMER,
        "3D Action Shooter Third-Person": ExcelGenre.THIRD_PERSON_SHOOTER,
        "3D Adventure First-Person": ExcelGenre.ACTION_ADVENTURE,
        "3D Adventure First-Person Open-World": ExcelGenre.ACTION_ADVENTURE,
        "3D Adventure First-Person VR": ExcelGenre.ACTION_ADVENTURE,
        "3D Adventure Third-Person": ExcelGenre.ACTION_ADVENTURE,
        "Action": ExcelGenre.ACTION,
        "Action Adventure": ExcelGenre.ACTION_ADVENTURE,
        "Action Adventure VR": ExcelGenre.ACTION_ADVENTURE,
        "Action Arcade": ExcelGenre.ARCADE,
        "Action Arcade VR": ExcelGenre.ARCADE,
        "Action Beat-'Em-Up": ExcelGenre.BEAT_EM_UP,
        "Action Fighting Wrestling": ExcelGenre.SPORTS,
        "Action First-Person Shooter Tactical": [
            ExcelGenre.FIRST_PERSON_SHOOTER,
            ExcelGenre.TACTICAL_SHOOTER,
        ],
        "Action First-Person Shooter Tactical VR": [
            ExcelGenre.FIRST_PERSON_SHOOTER,
            ExcelGenre.TACTICAL_SHOOTER,
        ],
        "Action Free-to-Play Role-Playing": ExcelGenre.ACTION,
        "Action Light-Gun Shooter": ExcelGenre.RAIL_SHOOTER,
        "Action Light-Gun Shooter VR": ExcelGenre.RAIL_SHOOTER,
        "Action Metroidvania Platformer": ExcelGenre.METROIDVANIA,
        "Action Puzzle": ExcelGenre.PUZZLE_ACTION,
        "Action Puzzle VR": ExcelGenre.PUZZLE_ACTION,
        "Action Role-Playing": ExcelGenre.ACTION_RPG,
        "Action Shooter Tactical Third-Person": [
            ExcelGenre.THIRD_PERSON_SHOOTER,
            ExcelGenre.TACTICAL_SHOOTER,
        ],
        "Action VR": ExcelGenre.ACTION,
        "Adventure": ExcelGenre.ADVENTURE,
        "Adventure Text-Based": ExcelGenre.TEXT_ADVENTURE,
        "Adventure VR": ExcelGenre.ADVENTURE,
        "Arcade Baseball Sports Team-Based": ExcelGenre.SPORTS,
        "Arcade Driving/Racing": ExcelGenre.RACING,
        "Arcade Driving/Racing VR": ExcelGenre.RACING,
        "Arcade Football (American) Sports Team-Based": ExcelGenre.SPORTS,
        "Arcade Golf Sports": ExcelGenre.SPORTS,
        "Arcade Golf Sports VR": ExcelGenre.SPORTS,
        "Arcade Soccer Sports Team-Based": ExcelGenre.SPORTS,
        "Basketball Simulation Sports Team-Based": ExcelGenre.SPORTS,
        "Boxing Sports": ExcelGenre.SPORTS,
        "Boxing Sports VR": ExcelGenre.SPORTS,
        "Card Game": ExcelGenre.CARD_GAME,
        "Compilation": ExcelGenre.COMPILATION,
        "Driving/Racing Simulation": ExcelGenre.RACING,
        "Driving/Racing Simulation VR": ExcelGenre.RACING,
        "Edutainment": ExcelGenre.EDUCATIONAL,
        "Fitness": ExcelGenre.SPORTS,
        "Flight Simulation": ExcelGenre.FLIGHT_SIMULATION,
        "Flight Simulation VR": ExcelGenre.FLIGHT_SIMULATION,
        "Football (American) Simulation Sports Team-Based": ExcelGenre.SPORTS,
        "Gambling": None,
        "Golf Simulation Sports": ExcelGenre.SPORTS,
        "Hidden Object Puzzle": ExcelGenre.HIDDEN_OBJECT,
        "Hunting/Fishing Sports": ExcelGenre.SPORTS,
        "Hunting/Fishing Sports VR": ExcelGenre.SPORTS,
        "MMO Role-Playing": ExcelGenre.MMORPG,
        "MOBA Strategy": None,
        "Management Role-Playing": ExcelGenre.SIMULATION,
        "Management Soccer Sports Team-Based": ExcelGenre.SIMULATION,
        "Management Strategy": ExcelGenre.SIMULATION,
        "Matching/Stacking Puzzle": ExcelGenre.PUZZLE,
        "Miscellaneous": ExcelGenre.EXPERIMENTAL,
        "Music/Rhythm": ExcelGenre.RHYTHM,
        "Music/Rhythm VR": ExcelGenre.RHYTHM,
        "Party/Minigame": ExcelGenre.MINIGAME_COLLECTION,
        "Pinball": ExcelGenre.PINBALL,
        "Puzzle": ExcelGenre.PUZZLE,
        "Real-Time Strategy": ExcelGenre.REAL_TIME_STRATEGY,
        "Real-Time Strategy VR": ExcelGenre.REAL_TIME_STRATEGY,
        "Roguelike Role-Playing": [ExcelGenre.ROGUELIKE, ExcelGenre.TURN_BASED_RPG],
        "Roguelike Simulation": [ExcelGenre.ROGUELIKE, ExcelGenre.SIMULATION],
        "Role-Playing": ExcelGenre.TURN_BASED_RPG,
        "Role-Playing VR": ExcelGenre.TURN_BASED_RPG,
        "Simulation": ExcelGenre.SIMULATION,
        "Simulation Strategy": ExcelGenre.SIMULATION,
        "Simulation VR": ExcelGenre.SIMULATION,
        "Skateboarding/Skating Sports": ExcelGenre.SPORTS,
        "Snowboarding/Skiing Sports": ExcelGenre.SPORTS,
        "Sports": ExcelGenre.SPORTS,
        "Sports Team-Based": ExcelGenre.SPORTS,
        "Sports Tennis": ExcelGenre.SPORTS,
        "Sports Wakeboarding/Surfing": ExcelGenre.SPORTS,
        "Strategy": ExcelGenre.STRATEGY,
        "Strategy Tactical Turn-Based": ExcelGenre.TURN_BASED_TACTICS,
        "Strategy Turn-Based": ExcelGenre.TURN_BASED_STRATEGY,
        "Strategy Turn-Based VR": ExcelGenre.TURN_BASED_STRATEGY,
        "Trivia/Board Game": [ExcelGenre.TRIVIA, ExcelGenre.BOARD_GAME],
    },
    DataSource.IGN: {
        "4X": ExcelGenre._4X,
        "Action": ExcelGenre.ACTION,
        "Action Figure": None,
        "Action-Adventure": ExcelGenre.ACTION_ADVENTURE,
        "Adult": None,
        "Adventure": ExcelGenre.ADVENTURE,
        "Anime": None,
        "Arcade": ExcelGenre.ARCADE,
        "Auto Battler": None,
        "Baseball": ExcelGenre.SPORTS,
        "Basketball": ExcelGenre.SPORTS,
        "Battle": None,
        "Battle Royale": None,
        "Beat 'Em Up": ExcelGenre.BEAT_EM_UP,
        "Blackjack": ExcelGenre.CARD_GAME,
        "Board": ExcelGenre.BOARD_GAME,
        "Board Game": ExcelGenre.BOARD_GAME,
        "Bowling": ExcelGenre.SPORTS,
        "Boxing": ExcelGenre.SPORTS,
        "Brick-Buster": ExcelGenre.PUZZLE_ACTION,
        "Bullet-Hell": ExcelGenre.SCROLLING_SHOOTER,
        "Card": ExcelGenre.CARD_GAME,
        "Card Collecting Game (CCG)": ExcelGenre.CARD_GAME,
        "Casino": None,
        "Casual": None,
        "Chess": ExcelGenre.BOARD_GAME,
        "City-Building": ExcelGenre.SIMULATION,
        "Comedy": None,
        "Compilation": ExcelGenre.COMPILATION,
        "Cooking": ExcelGenre.SIMULATION,
        "Crafting": ExcelGenre.SURVIVAL,
        "Crime": None,
        "Cult": None,
        "DLC / Expansion": None,
        "Dance": ExcelGenre.RHYTHM,
        "Dark Comedy": None,
        "Dating / Romance Game": None,
        "Deckbuilder": ExcelGenre.CARD_GAME,
        "Documentary": None,
        "Dodgeball": ExcelGenre.SPORTS,
        "Driving": ExcelGenre.RACING,
        "Dungeon Crawler": ExcelGenre.DUNGEON_CRAWLER,
        "Early Access": None,
        "Economic": ExcelGenre.SIMULATION,
        "Editor": ExcelGenre.GAME_CREATION,
        "Educational": ExcelGenre.EDUCATIONAL,
        "Endless Runner": ExcelGenre.RUNNER,
        "Episodic": None,
        "Escape Room": ExcelGenre.ADVENTURE,
        "Extreme": None,
        "Extreme Sports": ExcelGenre.SPORTS,
        "FMV": ExcelGenre.FMV,
        "Family": None,
        "Fantasy": None,
        "Farming / Gardening": ExcelGenre.SIMULATION,
        "Fashion": ExcelGenre.SIMULATION,
        "Fighting": ExcelGenre.FIGHTING,
        "First-Person": None,
        "Fishing": ExcelGenre.SPORTS,
        "Fitness": ExcelGenre.SPORTS,
        "Flight": ExcelGenre.FLIGHT_SIMULATION,
        "Football": ExcelGenre.SPORTS,
        "Formula One": ExcelGenre.RACING,
        "Free-to-Play": None,
        "Futuristic": None,
        "Gaming Competition": None,
        "Golf": ExcelGenre.SPORTS,
        "Graphic Novel": None,
        "Hacking": None,
        "Hidden Object": ExcelGenre.HIDDEN_OBJECT,
        "Horde Defense": None,
        "Horror": ExcelGenre.SURVIVAL_HORROR,
        "Horse Racing": ExcelGenre.SPORTS,
        "Hunting": ExcelGenre.SPORTS,
        "Indie": None,
        "Interactive": None,
        "Light Gun Shooter": ExcelGenre.RAIL_SHOOTER,
        "Live Service": None,
        "MMO": ExcelGenre.MMORPG,
        "Match-3": ExcelGenre.PUZZLE,
        "Match-4": ExcelGenre.PUZZLE,
        "Maze": ExcelGenre.ARCADE,
        "Metroidvania": ExcelGenre.METROIDVANIA,
        "Music": ExcelGenre.RHYTHM,
        "Mystery": None,
        "Nonogram": ExcelGenre.PUZZLE,
        "Off-Road": ExcelGenre.RACING,
        "Online": None,
        "Open-World": None,
        "Other": None,
        "Party": ExcelGenre.MINIGAME_COLLECTION,
        "Persistent Online": None,
        "Pinball": ExcelGenre.PINBALL,
        "Platformer": ExcelGenre.SIDE_SCROLLING_PLATFORMER,
        "Point-and-Click": ExcelGenre.ADVENTURE,
        "Productivity": None,
        "Puzzle": ExcelGenre.PUZZLE,
        "RPG": ExcelGenre.TURN_BASED_RPG,
        "Racing": ExcelGenre.RACING,
        "Rail Shooter": ExcelGenre.RAIL_SHOOTER,
        "Real-Time": None,
        "Reality": None,
        "Remake": None,
        "Remaster": None,
        "Retro Console": None,
        "Rhythm": ExcelGenre.RHYTHM,
        "Roguelike": ExcelGenre.ROGUELIKE,
        "Roguelite": ExcelGenre.ROGUELIKE,
        "Romance": None,
        "Romantic Comedy": None,
        "SHMUP": ExcelGenre.SCROLLING_SHOOTER,
        "Saboteur": None,
        "Sampler": None,
        "Sci-Fi": None,
        "Shooter": ExcelGenre.SHOOTER,
        "Short-Form": None,
        "Simulation": ExcelGenre.SIMULATION,
        "Skateboarding": ExcelGenre.SPORTS,
        "Skiing": ExcelGenre.SPORTS,
        "Snowboarding": ExcelGenre.SPORTS,
        "Soccer": ExcelGenre.SPORTS,
        "Soulslike": ExcelGenre.ACTION_RPG,
        "Sports": ExcelGenre.SPORTS,
        "Stealth": ExcelGenre.STEALTH_ACTION,
        "Strategy": ExcelGenre.STRATEGY,
        "Superhero": None,
        "Surfing": ExcelGenre.SPORTS,
        "Survival": ExcelGenre.SURVIVAL,
        "Table Tennis": ExcelGenre.SPORTS,
        "Tennis": ExcelGenre.SPORTS,
        "Text-Based": ExcelGenre.TEXT_ADVENTURE,
        "Third-Person": None,
        "Thriller": None,
        "Top-Down Shooter": ExcelGenre.SCROLLING_SHOOTER,
        "Tower Defense": ExcelGenre.TOWER_DEFENSE,
        "Trading Card Game (TCG)": ExcelGenre.CARD_GAME,
        "Trivia": ExcelGenre.TRIVIA,
        "Turn-Based": None,
        "Twin-Stick": ExcelGenre.TWIN_STICK_SHOOTER,
        "Typing": None,
        "Video": None,
        "Virtual Pet": ExcelGenre.SIMULATION,
        "Visual Novel": ExcelGenre.VISUAL_NOVEL,
        "Volleyball": ExcelGenre.SPORTS,
        "Western": None,
        "Word Game": ExcelGenre.PUZZLE,
        "Wrestling": ExcelGenre.SPORTS,
    },
    DataSource.LAUNCHBOX: {
        "Action": ExcelGenre.ACTION,
        "Adventure": ExcelGenre.ADVENTURE,
        "Beat 'em Up": ExcelGenre.BEAT_EM_UP,
        "Board Game": ExcelGenre.BOARD_GAME,
        "Casino": None,
        "Compilation": ExcelGenre.COMPILATION,
        "Construction and Management Simulation": ExcelGenre.SIMULATION,
        "Education": ExcelGenre.EDUCATIONAL,
        "Fighting": ExcelGenre.FIGHTING,
        "Flight Simulator": ExcelGenre.FLIGHT_SIMULATION,
        "Horror": ExcelGenre.SURVIVAL_HORROR,
        "Life Simulation": ExcelGenre.SIMULATION,
        "MMO": ExcelGenre.MMORPG,
        "Music": ExcelGenre.RHYTHM,
        "Party": ExcelGenre.MINIGAME_COLLECTION,
        "Pinball": ExcelGenre.PINBALL,
        "Platform": ExcelGenre.SIDE_SCROLLING_PLATFORMER,
        "Puzzle": ExcelGenre.PUZZLE,
        "Racing": ExcelGenre.RACING,
        "Role-Playing": ExcelGenre.TURN_BASED_RPG,
        "Sandbox": None,
        "Shooter": ExcelGenre.SHOOTER,
        "Sports": ExcelGenre.SPORTS,
        "Stealth": ExcelGenre.STEALTH_ACTION,
        "Strategy": ExcelGenre.STRATEGY,
        "Vehicle Simulation": ExcelGenre.RACING,
        "Visual Novel": ExcelGenre.VISUAL_NOVEL,
    },
    DataSource.MOBY_GAMES: {
        "4X": ExcelGenre._4X,
        "Action RPG": ExcelGenre.ACTION_RPG,
        "Arcade": ExcelGenre.ARCADE,
        "Artillery": None,
        "Beat 'em up / brawler": ExcelGenre.BEAT_EM_UP,
        "Board game": ExcelGenre.BOARD_GAME,
        "Cards / tiles": ExcelGenre.CARD_GAME,
        "Chess": ExcelGenre.BOARD_GAME,
        "City building / construction simulation": ExcelGenre.SIMULATION,
        "Dating simulation": None,
        "Falling block puzzle": ExcelGenre.PUZZLE,
        "Fighting": ExcelGenre.FIGHTING,
        "Gambling elements": None,
        "Game show / trivia / quiz": ExcelGenre.TRIVIA,
        "Graphic adventure": ExcelGenre.ADVENTURE,
        "Hack and slash": ExcelGenre.HACK_AND_SLASH,
        "Hidden object": ExcelGenre.HIDDEN_OBJECT,
        "Hunting": ExcelGenre.SPORTS,
        "Interactive book": ExcelGenre.ADVENTURE,
        "Interactive fiction / text adventure": ExcelGenre.TEXT_ADVENTURE,
        "Japanese-style RPG (JRPG)": ExcelGenre.TURN_BASED_RPG,
        "Japanese-style adventure": ExcelGenre.ADVENTURE,
        "Life / social simulation": ExcelGenre.SIMULATION,
        "Managerial / business simulation": ExcelGenre.SIMULATION,
        "Massively Multiplayer": ExcelGenre.MMORPG,
        "Mental training": ExcelGenre.EDUCATIONAL,
        "Metroidvania": ExcelGenre.METROIDVANIA,
        "Mini-games": ExcelGenre.MINIGAME_COLLECTION,
        "Music / rhythm": ExcelGenre.RHYTHM,
        "Paddle / Pong": ExcelGenre.ARCADE,
        "Party game": ExcelGenre.MINIGAME_COLLECTION,
        "Pinball": ExcelGenre.PINBALL,
        "Platform": ExcelGenre.SIDE_SCROLLING_PLATFORMER,
        "Puzzle elements": ExcelGenre.PUZZLE,
        "Quick Time Events (QTEs)": None,
        "RPG elements": None,
        "Rail shooter": ExcelGenre.RAIL_SHOOTER,
        "Real-time strategy (RTS)": ExcelGenre.REAL_TIME_STRATEGY,
        "Real-time tactics (RTT)": ExcelGenre.REAL_TIME_TACTICS,
        "Roguelike": ExcelGenre.ROGUELIKE,
        "Sandbox / open world": None,
        "Shooter": ExcelGenre.SHOOTER,
        "Stealth": ExcelGenre.STEALTH_ACTION,
        "Survival horror": ExcelGenre.SURVIVAL_HORROR,
        "Tactical RPG": ExcelGenre.STRATEGY_RPG,
        "Tactical shooter": ExcelGenre.TACTICAL_SHOOTER,
        "Tile matching puzzle": ExcelGenre.PUZZLE,
        "Time management": ExcelGenre.SIMULATION,
        "Timed input": None,
        "Tower defense": ExcelGenre.TOWER_DEFENSE,
        "Trading / collectible card": ExcelGenre.CARD_GAME,
        "Tricks / stunts": None,
        "Turn-based strategy (TBS)": ExcelGenre.TURN_BASED_STRATEGY,
        "Turn-based tactics (TBT)": ExcelGenre.TURN_BASED_TACTICS,
        "Visual novel": ExcelGenre.VISUAL_NOVEL,
        "Wargame": ExcelGenre.GRAND_STRATEGY,
        "Word construction": ExcelGenre.PUZZLE,
    },
}
