from typing import Dict, Optional, Set
from excel_game import ExcelPlatform

PLATFORM_SHORT_NAMES: Dict[Optional[ExcelPlatform], str] = {
    None: "TBD",
    ExcelPlatform._3DO: "3DO",
    ExcelPlatform.ACORN_ARCHIMEDES: "ARCH",
    ExcelPlatform.ACORN_ATOM: "ATOM",
    ExcelPlatform.ACORN_ELECTRON: "ELEC",
    ExcelPlatform.ACTION_MAX: "AM",
    ExcelPlatform.AMAZON_FIRE_TV: "FIRE",
    ExcelPlatform.AMSTRAD_CPC: "CPC",
    ExcelPlatform.AMSTRAD_PCW: "PCW",
    ExcelPlatform.ANDROID: "ANDR",
    ExcelPlatform.APPLE_II: "APL2",
    ExcelPlatform.APPLE_IIGS: "IIGS",
    ExcelPlatform.ARCADE: "ARC",
    ExcelPlatform.ARCADIA_2001: "A2K1",
    ExcelPlatform.ARDUBOY: "ARDU",
    ExcelPlatform.ATARI_2600: "2600",
    ExcelPlatform.ATARI_5200: "5200",
    ExcelPlatform.ATARI_7800: "7800",
    ExcelPlatform.ATARI_8_BIT: "A800",
    ExcelPlatform.ATARI_JAGUAR: "JAG",
    ExcelPlatform.ATARI_JAGUAR_CD: "AJCD",
    ExcelPlatform.ATARI_LYNX: "LYNX",
    ExcelPlatform.ATARI_ST: "AST",
    ExcelPlatform.BANDAI_PIPPIN: "PIP",
    ExcelPlatform.BBC_MICRO: "BBC",
    ExcelPlatform.BREW: "BREW",
    ExcelPlatform.BROWSER: "BROW",
    ExcelPlatform.BS_X: "BSX",
    ExcelPlatform.CASIO_LOOPY: "LOOP",
    ExcelPlatform.COLECO_ADAM: "ADAM",
    ExcelPlatform.COLECOVISION: "CVIS",
    ExcelPlatform.COMMODORE_64: "C64",
    ExcelPlatform.COMMODORE_AMIGA: "AMI",
    ExcelPlatform.COMMODORE_AMIGA_CD32: "CD32",
    ExcelPlatform.COMMODORE_PET: "PET",
    ExcelPlatform.COMMODORE_PLUS_4: "CP4",
    ExcelPlatform.COMMODORE_VIC_20: "VIC",
    ExcelPlatform.DEDICATED_CONSOLE: "DED",
    ExcelPlatform.DOJA: "DOJA",
    ExcelPlatform.DRAGON_32_64: "DRAG",
    ExcelPlatform.DSIWARE: "DSIW",
    ExcelPlatform.DVD_PLAYER: "DVD",
    ExcelPlatform.EPOCH_SUPER_CASSETTE_VISION: "SCV",
    ExcelPlatform.E_READER: "ERD",
    ExcelPlatform.EVERCADE: "EVC",
    ExcelPlatform.EXEN: "EXEN",
    ExcelPlatform.EXIDY_SORCERER: "EXDY",
    ExcelPlatform.FAMICOM_DISK_SYSTEM: "FDS",
    ExcelPlatform.FM_TOWNS: "FMT",
    ExcelPlatform.FM_7: "FM7",
    ExcelPlatform.GAMATE: "GAM",
    ExcelPlatform.GAME_BOY: "GB",
    ExcelPlatform.GAME_BOY_ADVANCE: "GBA",
    ExcelPlatform.GAME_BOY_COLOR: "GBC",
    ExcelPlatform.GAME_COM: "GCOM",
    ExcelPlatform.GAMEPARK_32: "GP32",
    ExcelPlatform.GIZMONDO: "GIZ",
    ExcelPlatform.GOOGLE_STADIA: "STAD",
    ExcelPlatform.GP2X_WIZ: "GWIZ",
    ExcelPlatform.INTELLIVISION: "INTV",
    ExcelPlatform.HARTUNG_GAME_MASTER: "HGM",
    ExcelPlatform.HYPERSCAN: "HYP",
    ExcelPlatform.IOS: "IOS",
    ExcelPlatform.J2ME: "J2ME",
    ExcelPlatform.MAC_OS: "MAC",
    ExcelPlatform.MAGNAVOX_ODYSSEY_2: "ODY2",
    ExcelPlatform.MATTEL_AQUARIUS: "AQUA",
    ExcelPlatform.MEGA_DUCK: "MGD",
    ExcelPlatform.MICROVISION: "MVIS",
    ExcelPlatform.MOPHUN: "MOPH",
    ExcelPlatform.MSX: "MSX",
    ExcelPlatform.MSX2: "MSX2",
    ExcelPlatform.MSX_TURBO_R: "MSXT",
    ExcelPlatform.NEC_PC_6001: "PC60",
    ExcelPlatform.NEC_PC_8801: "PC88",
    ExcelPlatform.NEC_PC_9801: "PC98",
    ExcelPlatform.NEO_GEO: "NG",
    ExcelPlatform.NEO_GEO_CD: "NGCD",
    ExcelPlatform.NEO_GEO_POCKET: "NGP",
    ExcelPlatform.NEO_GEO_POCKET_COLOR: "NGPC",
    ExcelPlatform.NES: "NES",
    ExcelPlatform.NEW_NINTENDO_3DS: "N3DS",
    ExcelPlatform.N_GAGE: "NGE",
    ExcelPlatform.N_GAGE_2_0: "NGE2",
    ExcelPlatform.NINTENDO_3DS: "3DS",
    ExcelPlatform.NINTENDO_64: "N64",
    ExcelPlatform.NINTENDO_64DD: "64DD",
    ExcelPlatform.NINTENDO_DS: "NDS",
    ExcelPlatform.NINTENDO_DSI: "DSI",
    ExcelPlatform.NINTENDO_GAMECUBE: "GCN",
    ExcelPlatform.NINTENDO_POKEMON_MINI: "POKE",
    ExcelPlatform.NINTENDO_SWITCH: "NS",
    ExcelPlatform.NINTENDO_WII: "WII",
    ExcelPlatform.NINTENDO_WII_U: "WIIU",
    ExcelPlatform.NUON: "NUON",
    ExcelPlatform.OCULUS_QUEST: "OQ",
    ExcelPlatform.ORIC: "ORIC",
    ExcelPlatform.OS_2: "OS2",
    ExcelPlatform.OUYA: "OUYA",
    ExcelPlatform.PALM_OS: "PALM",
    ExcelPlatform.PC: "PC",
    ExcelPlatform.PC_FX: "PCFX",
    ExcelPlatform.PDP_10: "PDP",
    ExcelPlatform.PHILIPS_CD_I: "CDI",
    ExcelPlatform.PIONEER_LASERACTIVE: "LAS",
    ExcelPlatform.PLAYDATE: "PD",
    ExcelPlatform.PLAYDIA: "PDIA",
    ExcelPlatform.PLAYSTATION: "PSX",
    ExcelPlatform.PLAYSTATION_2: "PS2",
    ExcelPlatform.PLAYSTATION_3: "PS3",
    ExcelPlatform.PLAYSTATION_4: "PS4",
    ExcelPlatform.PLAYSTATION_5: "PS5",
    ExcelPlatform.PLAYSTATION_NETWORK: "PSN",
    ExcelPlatform.PLAYSTATION_PORTABLE: "PSP",
    ExcelPlatform.PLAYSTATION_VITA: "VITA",
    ExcelPlatform.RISC_PC: "RISC",
    ExcelPlatform.SEGA_32X: "32X",
    ExcelPlatform.SEGA_CD: "SCD",
    ExcelPlatform.SEGA_DREAMCAST: "DC",
    ExcelPlatform.SEGA_GAME_GEAR: "GG",
    ExcelPlatform.SEGA_GENESIS: "GEN",
    ExcelPlatform.SEGA_MASTER_SYSTEM: "SMS",
    ExcelPlatform.SEGA_PICO: "PICO",
    ExcelPlatform.SEGA_SATURN: "SAT",
    ExcelPlatform.SEGA_SG_1000: "SG1K",
    ExcelPlatform.SHARP_X1: "X1",
    ExcelPlatform.SHARP_X68000: "X68K",
    ExcelPlatform.SNES: "SNES",
    ExcelPlatform.SUPER_ACAN: "ACAN",
    ExcelPlatform.SUPERGRAFX: "SG",
    ExcelPlatform.SYMBIAN: "SYMB",
    ExcelPlatform.TAPWAVE_ZODIAC: "ZOD",
    ExcelPlatform.THUMBY: "TBY",
    ExcelPlatform.THUMBY_COLOR: "TBYC",
    ExcelPlatform.TIMETOP_GAMEKING: "GK",
    ExcelPlatform.TIMETOP_GAMEKING_III: "GK3",
    ExcelPlatform.TRS_80_COLOR_COMPUTER: "COCO",
    ExcelPlatform.TURBOGRAFX_16: "TG16",
    ExcelPlatform.TURBOGRAFX_CD: "TGCD",
    ExcelPlatform.TVOS: "TVOS",
    ExcelPlatform.VECTREX: "VEC",
    ExcelPlatform.VIRTUAL_BOY: "VB",
    ExcelPlatform.WATARA_SUPERVISION: "WSV",
    ExcelPlatform.WATCHOS: "WOS",
    ExcelPlatform.WIIWARE: "WIIW",
    ExcelPlatform.WINDOWS_MOBILE: "WINM",
    ExcelPlatform.WINDOWS_PHONE: "WINP",
    ExcelPlatform.WONDERSWAN: "WS",
    ExcelPlatform.WONDERSWAN_COLOR: "WSC",
    ExcelPlatform.XBOX: "XB",
    ExcelPlatform.XBOX_360: "360",
    ExcelPlatform.XBOX_ONE: "XBO",
    ExcelPlatform.XBOX_SERIES_X_S: "XBSX",
    ExcelPlatform.ZEEBO: "ZEE",
    ExcelPlatform.ZX_SPECTRUM: "ZX",
}


HANDHELD_PLATFORMS: Set[ExcelPlatform] = set(
    [
        ExcelPlatform._3DO,
        ExcelPlatform.ARCADE,
        ExcelPlatform.ATARI_2600,
        ExcelPlatform.ATARI_5200,
        ExcelPlatform.ATARI_7800,
        ExcelPlatform.ATARI_JAGUAR,
        ExcelPlatform.ATARI_JAGUAR_CD,
        ExcelPlatform.ATARI_LYNX,
        ExcelPlatform.BS_X,
        ExcelPlatform.COLECOVISION,
        ExcelPlatform.DSIWARE,
        ExcelPlatform.FAMICOM_DISK_SYSTEM,
        ExcelPlatform.GAME_BOY,
        ExcelPlatform.GAME_BOY_ADVANCE,
        ExcelPlatform.GAME_BOY_COLOR,
        ExcelPlatform.INTELLIVISION,
        ExcelPlatform.IOS,
        ExcelPlatform.NEO_GEO,
        ExcelPlatform.NEO_GEO_CD,
        ExcelPlatform.NEO_GEO_POCKET,
        ExcelPlatform.NEO_GEO_POCKET_COLOR,
        ExcelPlatform.NES,
        ExcelPlatform.NEW_NINTENDO_3DS,
        ExcelPlatform.NINTENDO_3DS,
        ExcelPlatform.NINTENDO_64,
        ExcelPlatform.NINTENDO_64DD,
        ExcelPlatform.NINTENDO_DS,
        ExcelPlatform.NINTENDO_GAMECUBE,
        ExcelPlatform.NINTENDO_POKEMON_MINI,
        ExcelPlatform.NINTENDO_SWITCH,
        ExcelPlatform.PC,
        ExcelPlatform.PLAYDATE,
        ExcelPlatform.PLAYSTATION,
        ExcelPlatform.PLAYSTATION_2,
        ExcelPlatform.PLAYSTATION_PORTABLE,
        ExcelPlatform.PLAYSTATION_VITA,
        ExcelPlatform.SEGA_32X,
        ExcelPlatform.SEGA_CD,
        ExcelPlatform.SEGA_DREAMCAST,
        ExcelPlatform.SEGA_GAME_GEAR,
        ExcelPlatform.SEGA_GENESIS,
        ExcelPlatform.SEGA_MASTER_SYSTEM,
        ExcelPlatform.SEGA_SATURN,
        ExcelPlatform.SEGA_SG_1000,
        ExcelPlatform.SNES,
        ExcelPlatform.SUPERGRAFX,
        ExcelPlatform.TURBOGRAFX_16,
        ExcelPlatform.TURBOGRAFX_CD,
        ExcelPlatform.VECTREX,
        ExcelPlatform.VIRTUAL_BOY,
        ExcelPlatform.WATARA_SUPERVISION,
        ExcelPlatform.WONDERSWAN,
        ExcelPlatform.WONDERSWAN_COLOR,
        ExcelPlatform.XBOX,
    ]
)

NON_STREAMABLE_PLATFORMS: Set[ExcelPlatform] = set(
    [
        ExcelPlatform.ANDROID,
        ExcelPlatform.IOS,
        ExcelPlatform.NEW_NINTENDO_3DS,
        ExcelPlatform.OCULUS_QUEST,
        ExcelPlatform.PLAYDATE,
        ExcelPlatform.PLAYSTATION_4,
        ExcelPlatform.PLAYSTATION_5,
        ExcelPlatform.TVOS,
        ExcelPlatform.WATCHOS,
    ]
)
